export enum LogLevel {
  ALL = "*",
  DEBUG = "DEBUG",
  INFO = "INFO",
  WARN = "WARN",
  ERROR = "ERROR",
}

export enum LogNamespace {
  AUTOWIRE = "AUTOWIRE",
  INJECTION_CONTAINER = "INJECTION_CONTAINER",
  CLASS_REGISTRY = "CLASS_REGISTRY",
  INJECTABLE_REPO = "INJECTABLE_REPO",
  INJECTABLE = "INJECTABLE",
  ENV = "ENV",
}
